### ISSUE TITLE
help with adding values to vader_lexicon.txt

### ISSUE THREAD

**Issue by pinkshades128** [cjhutto/vaderSentiment#138]
Can you please explain how you assigned values for terms? I want to add terms that my team commonly uses (such as acronyms and nouns). For example, in line 1 of vader_lexicon.txt the "$:" is given the values "-1.5	0.80623	[-1, -1, -1, -1, -3, -1, -3, -1, -2, -1]."

**Comment by cjhutto** [comment]
This information is provided already. Please review the README, and if desired the accompanying publication that is provided in the "additional resources".
