### ISSUE TITLE
Reduce time complexity of algorithm

### ISSUE THREAD

**Issue by georgeberry** [cjhutto/vaderSentiment#15]
Hey @cjhutto, I really like vader. I [sped up your algorithm for the NLTK package](https://github.com/nltk/nltk/blob/develop/nltk/sentiment/vader.py) and wanted to let you know, in case you want to incorporate changes into your original code. It reduces the time complexity from something like O(N^4) to O(N).

**Comment by cjhutto** [comment]
Awesome!  The new update here and pip install incorporates this excellent contribution.
