### ISSUE TITLE
Emoteicon decoding

### ISSUE THREAD

**Issue by Thicool** [cjhutto/vaderSentiment#16]
Hello together,

does somebody know if there is a simple way to turn utf8 smileys to the ones that the vader_sentiment_lexicon uses?

When i scrape instagram data, python displays the emoteicons the same way as the instgram website, but when i export those posts to csv, i need to decode them. 

Thanks for help

**Comment by cjhutto** [comment]
I've updated the dictionary file (vader_lexicon.txt) to be UTF-8 compliant with unicode encoding by default now.  This might help solve the issue.  Also, if you aren't already doing it, try encoding your exported csv file as well, e.g., for Python 3.x
```
import csv
with open('output_file_name', 'w', newline='', encoding='utf-8') as csv_file:
    writer = csv.writer(csv_file, delimiter=';')
    writer.writerow('my_utf8_string')
```
