### ISSUE TITLE
Duplicate emoticon in 'vader_sentiment_lexicon.txt'?

### ISSUE THREAD

**Issue by stevenengler** [cjhutto/vaderSentiment#17]
Hi, I noticed that `vader_sentiment_lexicon.txt` has the `:p` emoticon listed twice (both with hex value `3a 70`). They occur on lines [139](https://github.com/cjhutto/vaderSentiment/blob/master/vaderSentiment/vader_sentiment_lexicon.txt#L139) and [155](https://github.com/cjhutto/vaderSentiment/blob/master/vaderSentiment/vader_sentiment_lexicon.txt#L155). Each has slightly different sentiment valence values.

**Comment by cjhutto** [comment]
Thanks for finding this!  
It has to do with inadvertent conversion of upper/lowercase... :P versus :p 
The new update (with new pip install) fixes this and several other issues.
