### ISSUE TITLE
Emoticons UTF-8

### ISSUE THREAD

**Issue by kokojumbo** [cjhutto/vaderSentiment#22]
First of all, I really like your lib. It's powerful.
I used utf-8 twitter emoticons like  ❤️😂😫😊 and  all of them have neutral sentiment.
Maybe it is just my issue, but I tried using UTF-8 encoding in my code and it didn't help.
I think, it's a good idea to add them to **vader_lexicon.txt** and support UTF-8 emoticons. 

Nowadays, they are more popular in social media than standard emoticons (':)' , ':(' ,':D', etc.)
Please check this website:
http://unicode.org/emoji/charts/full-emoji-list.html
I think, it might increase VADER accuracy significantly. 

Do you plan to rewrite this code to Java to make it more popular?
I can help you with that.

**Comment by cjhutto** [comment]
I'm glad you're finding VADER to be useful.

I think adding the emoji list is a great idea - I'll work on getting validated sentiment scores and add them to the lexicon.

A previous version of VADER was ported to JAVA. It can be found at https://github.com/apanimesh061/VaderSentimentJava.

**Comment by kootenpv** [comment]
I would like to second (or third) it.

I found these: 😡😤 not to take any effect. I would probably categorise them as ":@" in the vader_lexicon. 

Do you have any ETA for the updated lexicon :)? I think it would really help!

**Comment by knil-sama** [comment]
I am currently using this library [emoji](https://github.com/carpedm20/emoji/) to handling unicode emotes.
If Vader accepts to rely on third party library I can work on a pull request for this.

**Comment by cjhutto** [comment]
@kokojumbo @kootenpv @knil-sama 
   A year and a day later, I got around to implementing support for emojis :)
use `> pip install --upgrade vaderSentiment` to give it a try!
