### ISSUE TITLE
Cleaning the sentences 

### ISSUE THREAD

**Issue by vishnuu** [cjhutto/vaderSentiment#23]
Hello all,

I am new  to sentiment analysis and vader. 
I have the following tweets:

tweet1=["@ComfortablySmug: \"I'm just saying millennials dont count as people &amp; should be jailed\"\n\"Wrong the Constitution says I do\"\n\"3rd amendmen…"]

tweet2= ["❦※ Girls Black dress Best Prices  https://t.co/d9G5IzPX9E"]

when i want to calculate the score for the above tweets, is it needed to cleanse the sentences in any way? or straightway could i use the  above sentences? 

Can i also have these symbols ?, !, ; , &, $  or should it be substituted with anything? 

Thanks in advance,
Vishnu

**Comment by cjhutto** [comment]
You don't need to clean the tweet - indeed, it is best if you leave the tweet exactly as it is, with all symbols.
