### ISSUE TITLE
ImportError: can't import name sentiment

### ISSUE THREAD

**Issue by BNeidecker** [cjhutto/vaderSentiment#25]
There is a closed issue that was very similar to the issue that I'm having but the fix there doesn't seem to be working here.  To be sure, I've uninstalled and resinstalled the software, upgraded pip, and checked the file permissions of the files.

WHAT'S HAPPENING:
1.  Installed vaderSentiment with an updated version of pip using:
python -m pip install vaderSentiment
2.  In my .py file I import like so:
from vaderSentiment.vaderSentiment import sentiment as vaderSentiment
3.  But, when I run I get:
Traceback (most recent call last):
  File "file.py", line 6, in <module>
    from vaderSentiment.vaderSentiment import sentiment as vaderSentiment
ImportError: cannot import name sentiment

WHAT ELSE I'VE TRIED:
1. importing with the following:
from vaderSentiment import sentiment as vaderSentiment
Yet I still get the same error...

Any help would be greatly appreciated.

**Comment by cjhutto** [comment]
I would suggest reading the documentation, especially the (updated for the new pip install) code examples provided.

https://github.com/cjhutto/vaderSentiment#python-code-example
