### ISSUE TITLE
newline and dropdown aren't working after pulling vadersentiment

### ISSUE THREAD

**Issue by tanayz** [cjhutto/vaderSentiment#3]
I followed the last issue posted here and compiled vadersentiment after disabling line 20 and after that I'm able to print out object,however some additional problems persist.

1.I am using anaconda spyder as editor and the dropdown that appears after pressing dot(.) isn't appearing anymore.

2.Also in the command prompt after entering a python command when I am pressing enter it's not going to new line and executing and rather showing the effect of pressing shift+enter.

Any work around for these?

**Comment by QuantVI** [comment]
I seem to be having a similar problem. Using python (2.7.10) from the command prompt, I can do the following
from vaderSentiment.vaderSentiment import sentiment as vaderSentiment
print vaderSentiment("This is a sentence")
and get output. However, when executing these lines from idle, after hitting enter on the print statement, I just get a new prompt line. It prints nothing. Ideas?

Also, what was the line-20 problem?

**Comment by cjhutto** [comment]
The new update has better compatibility with Python 3 and across different OSs.
