### ISSUE TITLE
Modification of the corpus

### ISSUE THREAD

**Issue by bradybray** [cjhutto/vaderSentiment#31]
Hi Guys;

I am curious if it is possible to modify the corpus? I wanted to ask before I go spelunking around the source code with no real clear direction.

Thanks!

Braden.

**Comment by bradybray** [comment]
Whoops. Nm. I found the lexicon and it all seems pretty straightforward.

**Comment by iontom** [comment]
Is there any way to just add to the list with a second list without modifying the library?

**Comment by Hiestaa** [comment]
@iontom Feel free to [fork it](https://help.github.com/articles/fork-a-repo/), and make your own experiments. You can later submit a PR on this repo if the change you make seems satisfying to you!
