### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by JasonCao8023** [cjhutto/vaderSentiment#32]
D:\python\Lib\site-packages\vaderSentiment>python vaderSentiment.py
Traceback (most recent call last):
  File "vaderSentiment.py", line 14, in <module>
    import math, re, string, requests, json
ImportError: No module named requests

**Comment by ommirandap** [comment]
It seems like you need to install the [requests library](http://docs.python-requests.org/en/master/user/install/#install) ;)

**Comment by krishh-konar** [comment]
Run this on your terminal:
`pip install requests`

**Comment by kaustav1996** [comment]
Close this issue
