### ISSUE TITLE
Vader gives wrong result for some sentences

### ISSUE THREAD

**Issue by Chitrank-Dixit** [cjhutto/vaderSentiment#36]
Hello Everyone, 

So far Vader has helped me a lot in polarizing the data, I am analyzing on. I got all the analysis right and really like its sentiment intensity scoring.

I am getting just one problem with the sentences like

"Without a doubt   excellent idea", 
"neg": 0.422, "neu": 0.281, "pos": 0.297

"No payment and returning problems" 
"neg": 0.62, "neu": 0.38, "pos": 0

It is giving wrong results

**Comment by cjhutto** [comment]
I've added "Without {a} doubt" to the list of negation tokens, so it should appropriately flip the sentiment polarity while maintaining the intensity calculations.  When I run my test, I now get the following:
`Without a doubt, excellent idea. {'neg': 0.305, 'pos': 0.451, 'compound': 0.296, 'neu': 0.244}`

For the second example, I would say that VADER is giving correct results... as written, the text appears to be a complaint about getting no payment as well as having problems returning.
