### ISSUE TITLE
many of  PRIMARY RESOURCES and  additional DATASETS AND TESTING RESOURCES are not in folders

### ISSUE THREAD

**Issue by Sandy4321** [cjhutto/vaderSentiment#41]
The package here includes PRIMARY RESOURCES (items 1-3) as well as additional DATASETS AND TESTING RESOURCES (items 4-12):

please help to find this additional files

**Comment by cjhutto** [comment]
Don't know what to tell you -- all of the files are exactly where I say they are, in the "[additional_resources](https://github.com/cjhutto/vaderSentiment/blob/master/additional_resources/hutto_ICWSM_2014.tar.gz)" directory - you can click the download button right on that page.  They are compressed into a tarball (.tar file extension), then further compressed into a Gnu Zipped archive (.gz file extension)... use your favorite file archiver/compressor/decompressor (I like [7-zip](http://www.7-zip.org/)) to get at the 13 additional resource files in that package.
