### ISSUE TITLE
Issue reading lexicon as UTF-8 does not seem to be reflected when downloading the package via pip

### ISSUE THREAD

**Issue by brettvanderwerff** [cjhutto/vaderSentiment#42]
Please let me know if I am doing something wrong. I tried installing the package (using ubuntu 16.04) by entering both:

 pip install vaderSentiment

 pip install --upgrade vaderSentiment

However, there is still an issue with the lexicon not being read explicitly as UTF-8. I ended up finding the change on the repo here in vaderSentiment.py and implementing it in the source code on my machine manually. Is there a reason the repo here is more up to date than what I am getting when I install via pip? Please let me know if this is my misunderstanding or a legitimate issue.

**Comment by cjhutto** [comment]
Pretty easy explanation, actually -- I updated my GitHub, and forgot to push the update to PiPy.  Thanks for the heads up.

**Comment by brettvanderwerff** [comment]
I really admire your project I am glad I could help :)

**Comment by cjhutto** [comment]
@brettvanderwerff 
    Updated VADER to provide support for sentiment analysis of UTF-8 text containing emojis, and remembered to also push the update to PyPi.  Should be able to simply use `> pip install --upgrade vaderSentiment` for the latest.  Again, thanks for the heads up!
