### ISSUE TITLE
Confirming Threshold for Compound.

### ISSUE THREAD

**Issue by naveenjafer** [cjhutto/vaderSentiment#44]
The Readme file states that for neutral comment, vader needs the compound score to be below <0.05 and >-0.05, but the JS port mentions the thresholds as <0.5 and >-0.5, can someone clarify as to which one it is?

**Comment by cjhutto** [comment]
The entire compound score goes from -1 to 1, with 0 being neutral... so one would expect the thresholds  for neutral to be very close to zero, allowing for only a little variance.  Also, the published paper that the code is based on states that the thresholds for neutral are +-0.05.

**Comment by naveenjafer** [comment]
Thank you for confirming that :)
