### ISSUE TITLE
Source code for Vader Gold Lexicon creation

### ISSUE THREAD

**Issue by naveenjafer** [cjhutto/vaderSentiment#45]
I read the paper on which the Vader paper is implemented and I wanted to know if the code that converts the various datasets into the gold standard Lexicon list is available Openly? I would like to modify the existing datasets that Vader Uses to suit one of my use cases. @cjhutto Any inputs on the same?

**Comment by cjhutto** [comment]
Hi @naveenjafer -- the gold standard labeled data are all available within the "[additional resources](https://github.com/cjhutto/vaderSentiment/tree/master/additional_resources)" directory on the same GitHub Repo.  They are compressed first as a tarball and then as a GZ archive, so you will need to use your favorite file archiver software (I like [7-Zip](https://www.7-zip.org/)) and decompress from multiple levels.

**Comment by naveenjafer** [comment]
Thank you @cjhutto
