### ISSUE TITLE
Negation case-sensitivity

### ISSUE THREAD

**Issue by zHaytam** [cjhutto/vaderSentiment#46]
Hello,

Today I randomly tried to evaluate the following sentence: 'Not bad at all'. To my surprise, the compound was negative so I was trying to find out why would it.

After a quick read of the source code, I understood that Vader only handles lowercase negation.
Is there any solution to this?

A first instect is to .lower the whole text, but that would make things terrible, I'll be losing some key-features of Vader like  GOOD vs good etc..

I'm thinking (as a last resort) to split the words, check NEGATE contains their lowercase form and re-write the sentence with the negations in lowercase, but I'm hopping for a better solution.

Thank you.

**Comment by cjhutto** [comment]
Oh -- GREAT CATCH!  That case should absolutely should be caught (and it was correctly handled in the former Python 2.7 version of VADER) -- I think it got lost in the shuffle when we modularized for speed/performance increases while updating for Python 3... at any rate, the solution is pretty simple, I'll update the function that checks for negation to compare lowercase versions of input words to negation words.  (That way, we won't lose the ability to detect capitalization emphasis and such).

Again - thanks for the heads up!  I'll push the update soon.

**Comment by zHaytam** [comment]
Glad I could help. Is there a date for the update? Not trying to rush you or anything, I just want to know if I should keep my solution or just wait for the update 😄

**Comment by cjhutto** [comment]
About to push it out this evening...

**Comment by cjhutto** [comment]
@zHaytam it should be ready to go using `pip install --upgrade vaderSentiment`. 

Thanks!
