### ISSUE TITLE
Wrong score for sentence like this...

### ISSUE THREAD

**Issue by pchc2005** [cjhutto/vaderSentiment#48]
Hi, 

I am currently working on a project which need to analyze emails. 
I have found a case that may help to enrich this library. 

> Pls  note  we still    have no sight   fro your inv and   pls kindly make your positive support to the customer

The score of this is `{'pos': 0.428, 'neu': 0.495, 'neg': 0.078, 'compound': 0.836}`.
Semantically, this should be a negative statement on requiring a more positive support. Is it possible to make this correct with vaderSentiment?

Thanks, 
Peter

**Comment by mxchinegod** [comment]
Try an example that's not broken English. This isn't meant to work with a fundamentally poor understanding of language.

Frankly I don't even understand the first half of this message and while I understand the following:

"kindly make your positive support to the customer"

it's bizarre and redundant. You have to have good data for an analysis tool to help. What you've shown here is very bad data that even a human would have trouble understanding the sentiment until lots of inspection.
