### ISSUE TITLE
Using own lexicon 

### ISSUE THREAD

**Issue by shah0150** [cjhutto/vaderSentiment#49]
Hello, 

Is there a way we can use our own lexicon in Vader sentiment? If so how can one achieve this task? 

We are focusing on Sports based lexicon.

**Comment by cjhutto** [comment]
Yes - there absolutely is a way to either add your own data to the existing lexicon set, or to have your own completely separate lexicon set. If you want to be rigorous, follow the methods discussed in the paper that is referenced on the home page... if you just want to add more items and scores to the existing lexicon, you simply insert them into (your own local or forked copy) of the lexicon text file, using a tab to delimit the term and it's sentiment valence...

**Comment by senjed** [comment]
Hi, 
I have a list of positive and negative domain specific lexicon.  I noticed that I need to have a valance score associated with them in order to add them to the existing Vader lexicon file. Can you please let me know how I can compute those scores?
