### ISSUE TITLE
Error message..

### ISSUE THREAD

**Issue by sungmoonc** [cjhutto/vaderSentiment#5]
When I try the sample code, I get the following error message. How should I fix it? Python 3.5.0 on Mac.

Traceback (most recent call last):
  File "vader_sentiment.py", line 3, in <module>
    from vaderSentiment.vaderSentiment import sentiment as vaderSentiment
  File "/Users/sungmoon/.pyenv/versions/3.5.0a4/lib/python3.5/site-packages/vaderSentiment/vaderSentiment.py", line 23
    return dict(map(lambda (w, m): (w, float(m)), [wmsr.strip().split('\t')[0:2] for wmsr in open(f) ]))
                           ^
SyntaxError: invalid syntax

**Comment by sungmoonc** [comment]
It seems like Python 3.5 new grammar issue. http://stackoverflow.com/questions/15712210/python-3-2-lambda-syntax-error How do I fix that?

**Comment by guitarfrk75** [comment]
I have the same issue. It appears to be driven by the change from Python 2 to 3. To correct the issue, change this part of line 23 from:
lambda (w, m): (w, float(m) 
to:
lambda wm: (wm[0], float(wm[1]) 

You also have to add parentheses around the print statements on lines 358 to 363 and I had to commend out reload(sys) on line 20.

It now appears to be working, but watch the tutorial code for other differences between 2 and 3.

**Comment by sungmoonc** [comment]
This is awesome. Thanks a lot!

**Comment by cjhutto** [comment]
thanks @sungmoonc and @guitarfrk75 - appreciate the effort!

**Comment by ghost** [comment]
@guitarfrk75  I did what you said, but got a new error:

```
UnicodeDecodeError                        Traceback (most recent call last)
 <ipython-input-34-6f8e4787c376> in <module>()
 ----> 1 from vaderSentiment.vaderSentiment import sentiment as vaderSentiment

 /Users/yobichi/mc2/lib/python3.5/site-packages/vaderSentiment/vaderSentiment.py in <module>()
      28 except:
      29     f = os.path.join(os.path.dirname(__file__),'vader_sentiment_lexicon.txt')
 ---> 30     word_valence_dict = make_lex_dict(f)
      31 
      32 # for removing punctuation

 /Users/yobichi/mc2/lib/python3.5/site-packages/vaderSentiment/vaderSentiment.py in make_lex_dict(f)
      21 
      22 def make_lex_dict(f):
 ---> 23     return dict(map(lambda wm: (wm[0], float(wm[1])), [wmsr.strip().split('\t')[0:2] for wmsr in open(f) ]))
      24 
      25 f = 'vader_sentiment_lexicon.txt' # empirically derived valence ratings for words, emoticons, slang, swear words, acronyms/initialisms

 /Users/yobichi/mc2/lib/python3.5/site-packages/vaderSentiment/vaderSentiment.py in <listcomp>(.0)
      21 
      22 def make_lex_dict(f):
 ---> 23     return dict(map(lambda wm: (wm[0], float(wm[1])), [wmsr.strip().split('\t')[0:2] for wmsr in open(f) ]))
      24 
      25 f = 'vader_sentiment_lexicon.txt' # empirically derived valence ratings for words, emoticons, slang, swear words, acronyms/initialisms

 /Users/yobichi/mc2/bin/../lib/python3.5/encodings/ascii.py in decode(self, input, final)
      24 class IncrementalDecoder(codecs.IncrementalDecoder):
      25     def decode(self, input, final=False):
 ---> 26         return codecs.ascii_decode(input, self.errors)[0]
      27 
      28 class StreamWriter(Codec,codecs.StreamWriter):

 UnicodeDecodeError: 'ascii' codec can't decode byte 0xde in position 6573: ordinal not in range(128)
```

Do you have any idea? Thanks!
