### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by esitharth** [cjhutto/vaderSentiment#50]
Im getting this error while compiling SentimentIntensityAnalyzer()

ErrorLog:
venv/local/lib/python2.7/site-packages/vaderSentiment/vaderSentiment.py", line 212, in __init__
    with open(lexicon_full_filepath, encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by cjhutto** [comment]
try adding this to your list of imports to make it backward compatible for Python 2.7:

from io import open

**Comment by esitharth** [comment]
Thank you for your quick response. Did that. Worked like a charm.

**Comment by Kprzeorski** [comment]
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
    from io import open
    analyzer = SentimentIntensityAnalyzer()

ERROR:

    TypeErrorTraceback (most recent call last)
    <ipython-input-8-c96d329cbe73> in <module>()
          1 from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
          2 from io import open
    ----> 3 analyzer = SentimentIntensityAnalyzer()

    /home/kap/anaconda3/envs/py36/lib/python2.7/site-packages/vaderSentiment/vaderSentiment.pyc in 
    __init__(self, lexicon_file, emoji_lexicon)
        210         _this_module_file_path_ = os.path.abspath(getsourcefile(lambda: 0))
        211         lexicon_full_filepath = os.path.join(os.path.dirname(_this_module_file_path_), lexicon_file)
    --> 212         with open(lexicon_full_filepath, encoding='utf-8') as f:
        213             self.lexicon_full_filepath = f.read()
        214         self.lexicon = self.make_lex_dict()

    TypeError: 'encoding' is an invalid keyword argument for this function

I tried running the 3 line code inside a Jupyter notebook with python 3.6 and outside of jupyter in a terminal within python 2.7 and produced the same error.  I used Ubuntu OS.  Maybe put 'from io import open' in the vaderSentiment.py file?  I would need instructions to produce complied bytecode  to overwrite the existing one.....  I've never done that before.  Any suggestions or solutions?

**Comment by sunit1409** [comment]
sudo nano /home/kap/anaconda3/envs/py36/lib/python2.7/site-packages/vaderSentiment/vaderSentiment.py



put    from io import open in this file not on yours

**Comment by rxng** [comment]
I am facing this issue as well.

> from io import open

This gets rid of the message 

> with open(lexicon_full_filepath, encoding='utf-8') as f:

But then now the error is showing for

> File "/usr/local/lib/python2.7/dist-packages/vaderSentiment/vaderSentiment.py", line 212, in __init__
> lexicon_full_filepath = os.path.join(os.path.dirname(_this_module_file_path_), lexicon_file)
> TypeError: 'encoding' is an invalid keyword argument for this function
