### ISSUE TITLE
Missing dependencies (requests)

### ISSUE THREAD

**Issue by martin-martin** [cjhutto/vaderSentiment#51]
Hello!
When attempting to run `vaderSentiment` after installing it in my venv with the suggested `pip install vaderSentiment`, I got the following error:

```
Traceback (most recent call last):
  File "rate.py", line 1, in <module>
    from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
  File "/Users/martin/Documents/codingnomads/nlpython/big_projects/rate-mds/env/lib/python3.6/site-packages/vaderSentiment/vaderSentiment.py", line 17, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Seems that `requests` is an implicit(?) dependency.
I looked for a `requirements.txt` but not sure that's how it works with packages up on PyPI.

My `pip freeze` suggests that a `requirements.txt` for `vaderSentiment` could look like this:

```
certifi==2018.4.16
chardet==3.0.4
idna==2.7
requests==2.19.1
urllib3==1.23
```

If this is helpful, I can create one and make a PR? But maybe there are other reasons for this not to be included that I am not aware of.

Let me know if this is something I can help with - would gladly do so :)

**Comment by ianthebeard** [comment]
I have the same issue. I can't get vaderSentiment.py to run at all. Several errors, and being new to Python, I have no idea how to troubleshoot.

**Comment by martin-martin** [comment]
Hi @ianthebeard, you can type `pip install requests` in your console to resolve this issue.

Then run VADER again. Hope this helps!

**Comment by ianthebeard** [comment]
Awesome! Thank you
