### ISSUE TITLE
Not predicting sentiment of emoticons correctly

### ISSUE THREAD

**Issue by Rishav09** [cjhutto/vaderSentiment#56]
It is not predicting inconsistent results on emoticons.For instance, when I am passing  this as '🙂' an argument, it is correctly predicting the outcome but on using same emoticons multiple times '🙂🙂',
it is giving neutral results.Similarly ,the same issue is arising in different cases of other emoji and sometimes ,it is not even detecting the single emoji too.

**Comment by ayushbits** [comment]
@cjhutto I am also facing the issue. Could you tell why is it happening ?

**Comment by ckw017** [comment]
The analyzer splits up the input by whitespace and looks for emoji among those tokens. So when it encounters a token like two smiling faces in a row, it will look for the token containing both faces in the emoji lexicon, fail to find it, and carry on. A fix for this would be to search for emoji on a character by character basis.

**Comment by ddugovic** [comment]
Does :smiley: :smiley: mean the same thing as :smiley: ?

**Comment by ckw017** [comment]
I feel like it should mean the same thing as if ":)" would be to ":) :)"

**Comment by Rishav09** [comment]
@ddugovic  No, it doesn't. 😃 😃 have more positive compound score than 😃 .
@ckw017  Yes, I realised, emoji's needs to be space separated for analyser to work.
