### ISSUE TITLE
Port to C#

### ISSUE THREAD

**Issue by ziad-akiki** [cjhutto/vaderSentiment#61]
Hello, well this isn't an issue but a port on C# is available at https://github.com/codingupastorm/vadersharp by [Jordan Andrews](https://github.com/codingupastorm). Personaly tested it and it's working fine.

As per your request in the [Readme](https://github.com/cjhutto/vaderSentiment/blob/master/README.rst) document, I'm just letting you know of this finding.

**Comment by cjhutto** [comment]
Awesome, thanks!
