### ISSUE TITLE
Add support for Facebook Emojis

### ISSUE THREAD

**Issue by Rosadojonathan** [cjhutto/vaderSentiment#62]
Hey there! 
I was using vaderSentiment to analyze Facebook comments on my ads and I realized that comments that used Facebook emojis were parsed as neutral `{'pos': 0.0, 'neg': 0.0, 'compound': 0.0, 'neu': 1.0}`
example -> ![image](https://user-images.githubusercontent.com/25138966/46789791-a7665200-cd3d-11e8-8745-44fbddefe90d.png)
`Plus de 50 euros de frais de réservation, je trouve ça très exagéré !!😡`
However, if I removed the Facebook emoji from a sentence that used those emojis I would get actual scores, for instance : `{'pos': 0.0, 'neu': 0.834, 'compound': -0.2465, 'neg': 0.166}`

Do you know why Facebook Emojis make the whole sentence neutral? Do you plan to add support for these emojis?

Thanks!

**Comment by cjhutto** [comment]
Got this fix in. Thanks!
