### ISSUE TITLE
NLTK's Vader version doesn't support sentiments of emoji's

### ISSUE THREAD

**Issue by Rishav09** [cjhutto/vaderSentiment#63]
On using the NLTK's version , the sentiments of emojis is not coming.

**Comment by cjhutto** [comment]
the NLTK administrators may not keep their code base as up to date as I update VADER.  This repo is likely the most recent roll-out, and I push regularly to the PiPy (so `pip install upgrade vaderSentiment` should work for the latest, usually)

**Comment by cjhutto** [comment]
The NLTK administrators may not keep their vader module as up to date (or maybe not as quickly as I make updates to vaderSentiment).  This repo will always have the latest version, and I push regularly to PyPi (so `pip install upgrade vaderSentiment` should work to get you the latest, most of the time, with maybe just a little lag behind this repo).

**Comment by jisnatitech** [comment]
Could not find a version that satisfies the requirement upgrade (from versions: )

**Comment by sohumsachathamakul** [comment]
@cjhutto - Emoji's seem to be only outputting neutral score as if it's not taking it into account emojis. Please find reproducible steps below:

1. In terminal: `pip install --upgrade vaderSentiment` 
2. In Jupyter notebook:
<img width="1172" alt="Screen Shot 2563-03-07 at 15 50 01" src="https://user-images.githubusercontent.com/47490307/76140288-591cc600-608b-11ea-8b86-5d3b2d68d07a.png">

**Comment by cjhutto** [comment]
So, NLTK lags PyPi (pip), which lags this repo... 

If you use
`pip install --upgrade vaderSentiment`
then make sure to import that version instead of the one from NLTK, e.g., 
```
from vaderSentiment import SentimentIntensityAnalyzer
vader = SentimentIntensityAnalyzer()
print(vader.polarity_scores("💋 and 😁 "))
```
`{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.7003}`

**Comment by rezabrizi** [comment]
@cjhutto  What can I do to use newly added emojis? 
As you can see below, sentence 2 and 3 have the same score, so seems like it is not recognizing the second emoji in sentence 3. 
![Screen Shot 2023-02-04 at 10 22 10 AM](https://user-images.githubusercontent.com/63474681/216778268-aedf9008-5421-4f04-b546-b64018c03658.png)
