### ISSUE TITLE
"To die for" misinterpreted

### ISSUE THREAD

**Issue by fcpenha** [cjhutto/vaderSentiment#67]
I have found this basic common expression which is misinterpreted by Vader:

`To die for.-------------- {'neg': 0.661, 'neu': 0.339, 'pos': 0.0, 'compound': -0.5994}`

Could you consider adding a new rule for that?

**Comment by AbtinZo** [comment]
These cases should be added to `special_case_idioms` list with a positive value. You can customize that list and add to it manually.

**Comment by fcpenha** [comment]
@AbtinZohrabi I am not sure how to add these. You mean that I have to change the source code?

**Comment by AbtinZo** [comment]
@fcpenha Yes, There's a variable in this file `vaderSentiment/vaderSentiment.py` called SPECIAL_CASE_IDIOMS. you have to add to this list

**Comment by ddugovic** [comment]
For ease of understanding & future development might it make sense to store `SENTIMENT_LADEN_IDIOMS` and `SPECIAL_CASE_IDIOMS` with their scores in CSV files?

(Longer-term a database might work even better, so users can easily add/change scores with which they disagree.)

**Comment by fcpenha** [comment]
Sincerely, I like the idea of having this as an optional parameter, which in this case would be a python dictionary. Then, you don't need to worry about changing source code, and just do `pip install` and be happy.

**Comment by AbtinZo** [comment]
@ddugovic That would be a good option

**Comment by cjhutto** [comment]
added to special case idiom rules
