### ISSUE TITLE
Doesn't predict negative sentiments as expected.

### ISSUE THREAD

**Issue by mirzhash** [cjhutto/vaderSentiment#68]
Vader gives wonderful results for Positive feedbacks but it doesn't predict negative feedbacks correctly such as 
1. 'This is not proper' 
2. i could not understand as to why the marks are deduced'
3. 'evaluation is not correct' 
and similar type of feedbacks.

Does anyone know of any hack or how to deal with such feedbacks?

**Comment by cjhutto** [comment]
Without context, there is nothing inherently negative about those sentences... VADER seems to be operating correctly (or as designed/expected). 

If you want VADER to be sensitive to context, then you probably want to do as others have done and train a ML model on domain specific sentiments.

**Comment by cjhutto** [comment]
You can always expand the lexicon to domain specific context by adding items to your copy of the (tab delimited) `vader_lexicon.txt` file.   For example, if you added lines for:
```
correct	1
proper	1
understand	1
```
... is one way to handle it, assuming in your context that those lexical items ALWAYS have a positive valence when they are used (in the initial creation of the lexicon, without context those items were deemed to be neutral).  (Note: VADER will handle it if they are negated in the sentence, e.g., 'not proper', 'not correct', and 'not understand' will flip the polarity of sentiment score automatically).

**Comment by mirzhash** [comment]
Thanks for the suggestion. I will add more words to the lexicon.
