### ISSUE TITLE
What language are supported? I can't find any mention of it.  

### ISSUE THREAD

**Issue by pierreconti** [cjhutto/vaderSentiment#77]

**Comment by besirkurtulmus** [comment]
It should be only English. At least that's what their paper says.

**Comment by AbtinZo** [comment]
> if you have access to the Internet, the demo has an example of how VADER can work with analyzing sentiment of texts in other languages (non-English text sentences).

It's only in English, but they believe it works pretty accurate if you translate from other languages into English (using some third-parties like google translate) and calculate the sentiment for translated text.

Other option is to translate dictionary and also rewrite grammatical rules into other language and customize the algorithm. I tried this for French and Spanish and it worked fine. One good thing about this method is that you're not going to rely on some other third party translators for each and every text (They are not free for high volumes and can become expensive). All you have to do it to translate and customize algorithm itself once and for all.
