### ISSUE TITLE
Sentiment storing

### ISSUE THREAD

**Issue by Panchal-Dakshesh** [cjhutto/vaderSentiment#80]
can we store the 4 emotion results in variable rather than displaying it on terminal, is there a way to do it ? if yes , help.

**Comment by AbtinZo** [comment]
What you mean by "4 emotion results" ?

**Comment by cjhutto** [comment]
If you check out the [Python code example right on the front page](https://github.com/cjhutto/vaderSentiment#python-code-example) of the README, you'll see one way to store results in a variable... it is just a simple python dictionary - so usage should be pretty straight forward for accessing any of the four measures you are interested in.
