### ISSUE TITLE
Adjective versions of booster dictionary adverbs don't appear in lexicon

### ISSUE THREAD

**Issue by sastoudt** [cjhutto/vaderSentiment#84]
Shouldn't the corresponding adjectives for the booster dictionary adverbs appear in the lexicon?

For example "tremendously" is in the booster dictionary but "tremendous" isn't in the lexicon. Same with "exceptionally" and "exceptional."

Or perhaps the adjective version should also be in the booster dictionary (tremendous flaw has different sentiment than tremendous effort)?

**Comment by cjhutto** [comment]
Great point! I've addressed this with additions of adjective forms of adverbs in the booster dictionary (for those not accounted for using empirically derived valence scores).
