### ISSUE TITLE
Not recognizing emojis when it is without space

### ISSUE THREAD

**Issue by matthewgson** [cjhutto/vaderSentiment#86]
I noticed a bug that VADER does not recognize emojis when it is attached to words or it is used without space. 

The codes shown in below link gives reproducible example. 
https://stackoverflow.com/questions/52110025/unable-to-predict-sentiment-of-emoticons

Hope this behavior is fixed soon.

**Comment by cjhutto** [comment]
Got this fixed.  Thanks for pointing it out!
