### ISSUE TITLE
Propose to make `requests` import local to where it's used

### ISSUE THREAD

**Issue by ksen0** [cjhutto/vaderSentiment#88]
Very minor nit: the `requests` module is not actually used except in running as application in CLI. To limit dependency complexity, I would like to use `vaderSentiment` without having to also require `requests` - which is, in fact, totally not necessary in the context I'm working in.

Propose to move `import requests` to `vaderSentiment.py:668`. Although local imports are not ideal, there is already a local import of `nltk` in that block

**Comment by cjhutto** [comment]
Good suggestion. Incorporated. Thanks!
