### ISSUE TITLE
vader_sentiment_lexicon.txt encoding

### ISSUE THREAD

**Issue by mp31415** [cjhutto/vaderSentiment#9]
There are two characters in vader_sentiment_lexicon.txt that are problematic when opening the file on Ubuntu. These are thorn symbols (currently lines 127 and 159). If the file is open in Notepad++ on Windows the detected encoding is ansi and switching it to utf-8 breaks these two symbols. At the same time on Ubuntu I guess default file encoding in 'open(f)' is utf-8 and open(f) fails with invalid characters. If these two characters are replaced with their correct utf-8 values after switching to utf-8 encoding in vader_sentiment_lexicon.txt, the problem is solved. (This file works fine when running it on Windows).

Thank you for the tool.

**Comment by cjhutto** [comment]
Thanks for pointing this out!  I've changed the default encoding for the dictionary file to be UTF-8 unicode compliant.  I hope this makes it easier to use VADER across different OSs.
