### ISSUE TITLE
Is it better to use pos, neu and neg to determine the sentiment?

### ISSUE THREAD

**Issue by bright1993ff66** [cjhutto/vaderSentiment#92]
Hi, I am working on an twitter sentiment classification task. I think the ```compound``` method does not work well in cases like the following:

text: "I am at ping chi street bus stop."

The result is like the following:

```Shell
{'pos': 0.0, 'neg': 0.268, 'compound': -0.296, 'neu': 0.732}
```
The ```stop``` here just means the bus stop. But the sentiment analyzer regards this as a negative notation...

**Comment by cjhutto** [comment]
Thanks for identifying this.  
Made a change that accounts for "bus stop", and is extensible as new cases are identified.
