### ISSUE TITLE
HTTPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by mvcduarte** [cjhutto/vaderSentiment#93]
After a few requests (< 100), it reaches "too many requests", probably due to the google translate API. 
Any idea how to overcome this issue?

Thanks in advance, 

Marcus

**Comment by cjhutto** [comment]
So - VADER does not inherently provide it's own translation.  The use of "My Memory Translation Service" from MY MEMORY NET (see:  http://mymemory.translated.net) is part of the demonstration showing (one way) for how to use VADER on non-English text.  (Please note the usage limits for number of requests:  http://mymemory.translated.net/doc/usagelimits.php)

I think it works pretty well, and if needed, a VADER user (who also wanted expanded translation service) could pay for the premium Google Translate API or some other translation service with a less restrictive request limit... or else use some other translation service.
