### ISSUE TITLE
How can someone further train this model?

### ISSUE THREAD

**Issue by paco020295** [cjhutto/vaderSentiment#96]
Hello,

Sorry. I am new to this library. I would like to know if there is an easy way of training this library (Manually obviously)

Because i am seeing the following values:
Very conveniently located just outside the exit point of Zurich Airport. 0.0
Typical Swiss cleanliness and precision is oozing from this lounge.-- 0.0

What woould you recommend me to do to improve the accuracy?

**Comment by cjhutto** [comment]
Hi @paco020295. The development of the VADER sentiment analysis lexicon as well as it's rule based analysis engine are described in the paper, as well as on this gihub.  Everything you should need to know is explained -- and you can extend VADER to your own liking.
